functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Сайт должен показывать уведомление об использовании cookie-файлов
  - Сайт должен отображать информацию о продавце  (ст. 9 п.1 Закон Российской Федерации «О защите прав потребителей»)
  - Сайт должен отображать информация по возврату товара "Закон РФ «О защите прав потребителей» от 07.02.1992 № 2300-1"
  - Пользователь должен иметь возможность зарегестрироваться на сайте
  - Пользователь должен иметь возможность просматривать свои заказы
